/* Auto Generated Code By AutoCodeGen Jabil © 2019 */
import { BaseModel } from '../base/base-model';
import { Constants, Numbers } from 'src/app/shared/constant/global';
import { SAPPartInspectionPlan } from './sap-part-inspection-plan';
import { WorkCell } from '../workcell/work-cell';
import { Commodity } from '../commodity/commodity';
import { AdminCertification } from '../admin-certification/admin-certification';
import { ProductLifeCycleStage } from '../product-life-cycle-stage/product-life-cycle-stage';
import { PartInspectionDrawingAttachment } from '../part-inspection-drawing-attachment/part-inspection-drawing-attachment';
import { User } from '../user/user';
import { PartInspectionAdminCertification } from '../part-inspection-admin-certification/part-inspection-admin-certification';
import { SAPSamplingPlanModel } from '../sap-models/sap-sampling-plan-model';
import { PartInspectionCertificationAttachment } from '../part-inspection-certification-attachment/part-inspection-certification-attachment';
import { PartInspectionSpecAttachment } from '../part-inspection-spec-attachment/part-inspection-spec-attachment';
import { MPositionToleranceModel } from './m-position-tolerance/m-position-tolerance-model';
import { LPositionToleranceModel } from './l-position-tolerance/l-position-tolerance-model';
import { MeasurementParameterModel } from './measurement-parameter/measurement-parameter-model';
import { MicroSectionParameterModel } from './micro-section-parameter/micro-section-parameter-model';
import { FunParameterModel } from './fun-parameter/fun-parameter-model';
import { PartInspectionBowTwistParameter } from '../part-inspection-bow-twist-parameter/part-inspection-bow-twist-parameter';
import { ResultOrientedTab } from '../result-oriented/result-oriented';
import { PartCountParameter } from '../part-count-parameter/part-count-parameter';
import { PartDateCode } from '../part-date-code/part-date-code';
import { Supplier } from '../supplier/supplier';
import { PartDrawingModel } from './part-drawing-model';
import { PartSpecModel } from './part-spec-model';
import { SAPPartInspectionPlanComments } from '../sap-part-inspection-plan-comments/sap-part-inspection-plan-comments';
import { PartTestReportTab } from '../part-test-report/part-test-report-tab-model';

export class UpdateSAPPartInspectionPlanModel extends BaseModel {
    partNo: string;
    partDescription: string;
    ip: string;
    siteIP: string;
    cafNo: string;
    isSafePart: boolean;
    workCellId: number;
    workCell: WorkCell;
    divisionModelNumber: string;
    genWI: string;
    refDoc: string;
    commodityId: number;
    commodity: Commodity;
    manufacturePartNumber: string;
    manufacturer: string;
    mediaCode: string;
    maskedMPN: string;
    adminCertificationId: number;
    adminCertifications: AdminCertification[];
    supplierId: number;
    supplier: Supplier;
    supplierContactId: number;
    supplierContact: User;
    jabilOwnerContact: string;
    productLifeCycleStage: ProductLifeCycleStage;
    productLifeCycleStageId: number;
    partInspectionDrawingAttachments: PartInspectionDrawingAttachment[];
    partInspectionSpecAttachments: PartInspectionSpecAttachment[];
    partInspectionCertificationAttachments: PartInspectionCertificationAttachment[];
    submittedByUserId: number;
    assignToUserId: number;
    submittedDate: Date;
    submittedBy: User;
    assignTo: User;
    comment: string;
    approveRejectedId: number;
    approveRejectedDate: Date;
    approveRejected: User;
    stateTypeId: number;
    addedAdminCertificateIds: PartInspectionAdminCertification[];
    removedAdminCertificateIds: PartInspectionAdminCertification[];
    sapPartInspectionPlanSamplingPlans: SAPSamplingPlanModel[];
    removedUploadSpecAttachmentsIds: number[];
    removedDrawingAttachmentIds: number[];
    removedSpecIds: number[];
    removedDrawingIds: number[];
    removedCertificationAttachmentIds: number[];
    ismpnMatched: boolean;
    mpnMaterialHERS: string;
    mpnReason: string;
    partMPositionTolerances: MPositionToleranceModel[];
    partLPositionTolerances: LPositionToleranceModel[];
    partMeasurementParameters: MeasurementParameterModel[];
    partMicrosectionParameters: MicroSectionParameterModel[];
    partFunParameters: FunParameterModel[];
    partInspectionBowTwistParameters: PartInspectionBowTwistParameter[];
    specTypeId: number;
    dataTypeId: number;
    partResultOrientedParameters: ResultOrientedTab[];
    partTestReportParameters: PartTestReportTab[];
    partCountParameters: PartCountParameter[];
    partDateCode: PartDateCode;
    partDateCodeId: number;
    partInspectionDrawings: PartDrawingModel[];
    partInspectionSpecifications: PartSpecModel[];
    ipSerialNumber: number;
    siteIPSerialNumber: number;
    partComments: SAPPartInspectionPlanComments[];
    referenceSAPPartInspectionPlanId: number;
    isRedefine: boolean;
    isSupplier: boolean;
    constructor(sAPPartInspectionPlan?: SAPPartInspectionPlan) {
        super(sAPPartInspectionPlan);
        if (sAPPartInspectionPlan) {
            this.partNo = sAPPartInspectionPlan.partNo;
            this.partDescription = sAPPartInspectionPlan.partDescription;
            this.ip = sAPPartInspectionPlan.ip;
            this.siteIP = sAPPartInspectionPlan.siteIP;
            this.cafNo = sAPPartInspectionPlan.cafNo;
            this.isSafePart = sAPPartInspectionPlan.isSafePart;
            this.workCellId = sAPPartInspectionPlan.workCellId;
            this.workCell = sAPPartInspectionPlan.workCell;
            this.divisionModelNumber = sAPPartInspectionPlan.divisionModelNumber;
            this.genWI = sAPPartInspectionPlan.genWI;
            this.refDoc = sAPPartInspectionPlan.refDoc;
            this.commodityId = sAPPartInspectionPlan.commodityId;
            this.commodity = sAPPartInspectionPlan.commodity;
            this.partInspectionDrawings = sAPPartInspectionPlan.partInspectionDrawings;
            this.partInspectionSpecifications = sAPPartInspectionPlan.partInspectionSpecifications;
            this.manufacturePartNumber = sAPPartInspectionPlan.manufacturePartNumber;
            this.manufacturer = sAPPartInspectionPlan.manufacturer;
            this.mediaCode = sAPPartInspectionPlan.mediaCode;
            this.maskedMPN = sAPPartInspectionPlan.maskedMPN;
            this.adminCertificationId = sAPPartInspectionPlan.adminCertificationId;
            this.adminCertifications = sAPPartInspectionPlan.adminCertifications;
            this.supplierId = sAPPartInspectionPlan.supplierId;
            this.supplier = sAPPartInspectionPlan.supplier;
            this.supplierContactId = sAPPartInspectionPlan.supplierContactId;
            this.supplierContact = sAPPartInspectionPlan.supplierContact;
            this.jabilOwnerContact = sAPPartInspectionPlan.jabilOwnerContact;
            this.productLifeCycleStageId = sAPPartInspectionPlan.productLifeCycleStageId;
            this.productLifeCycleStage = sAPPartInspectionPlan.productLifeCycleStage;
            this.assignTo = sAPPartInspectionPlan.assignTo;
            this.submittedDate = sAPPartInspectionPlan.submittedDate;
            this.comment = sAPPartInspectionPlan.comment;
            this.approveRejected = sAPPartInspectionPlan.approveRejected;
            this.approveRejectedId = sAPPartInspectionPlan.approveRejectedId === 0 ? null : sAPPartInspectionPlan.approveRejectedId ;
            this.assignToUserId = sAPPartInspectionPlan.assignToUserId === 0 ? null : sAPPartInspectionPlan.assignToUserId ;
            this.submittedByUserId = sAPPartInspectionPlan.submittedByUserId === 0 ? null : sAPPartInspectionPlan.submittedByUserId ;
            this.approveRejectedDate = sAPPartInspectionPlan.approveRejectedDate;
            this.addedAdminCertificateIds = sAPPartInspectionPlan.sAPPartInspectionPlanAdminCertifications;
            this.ismpnMatched = sAPPartInspectionPlan.ismpnMatched;
            this.mpnMaterialHERS = sAPPartInspectionPlan.mpnMaterialHERS;
            this.mpnReason = sAPPartInspectionPlan.mpnReason;
            this.partMPositionTolerances = sAPPartInspectionPlan.partMPositionTolerances;
            this.partLPositionTolerances = sAPPartInspectionPlan.partLPositionTolerances;
            this.partMeasurementParameters = sAPPartInspectionPlan.partMeasurementParameters;
            this.partMicrosectionParameters = sAPPartInspectionPlan.partMicrosectionParameters;
            this.partFunParameters = sAPPartInspectionPlan.partFunParameters;
            this.partResultOrientedParameters = sAPPartInspectionPlan.partResultOrientedParameters;
            this.partInspectionBowTwistParameters = sAPPartInspectionPlan.partInspectionBowTwistParameters;
            this.partTestReportParameters = sAPPartInspectionPlan.partTestReportParameters;
            this.partCountParameters = sAPPartInspectionPlan.partCountParameters;
            this.specTypeId = sAPPartInspectionPlan.specTypeId;
            this.dataTypeId = sAPPartInspectionPlan.dataTypeId;
            this.partDateCodeId = sAPPartInspectionPlan.partDateCodeId === 0 ? null : sAPPartInspectionPlan.partDateCodeId;
            this.ipSerialNumber = sAPPartInspectionPlan.ipSerialNumber;
            this.siteIPSerialNumber = sAPPartInspectionPlan.siteIPSerialNumber;
            this.partComments = sAPPartInspectionPlan.partComments;
            this.referenceSAPPartInspectionPlanId = sAPPartInspectionPlan.referenceSAPPartInspectionPlanId;
            this.isRedefine = sAPPartInspectionPlan.isRedefine;
            this.isSupplier = sAPPartInspectionPlan.isSupplier;
        } else {
            this.partNo = Constants.Empty;
            this.partDescription = Constants.Empty;
            this.ip = Constants.Empty;
            this.siteIP = Constants.Empty;
            this.cafNo = Constants.Empty;
            this.isSafePart = false;
            this.workCellId = null;
            this.workCell = null;
            this.divisionModelNumber = Constants.Empty;
            this.genWI = Constants.Empty;
            this.refDoc = Constants.Empty;
            this.commodityId = 0;
            this.commodity = null;
            this.manufacturePartNumber = Constants.Empty;
            this.manufacturer = Constants.Empty;
            this.mediaCode = Constants.Empty;
            this.maskedMPN = Constants.Empty;
            this.adminCertificationId = null;
            this.adminCertifications = [];
            this.supplierId = null;
            this.supplier = null;
            this.supplierContactId = null;
            this.supplierContact = null;
            this.jabilOwnerContact = Constants.Empty;
            this.productLifeCycleStageId = null;
            this.productLifeCycleStage = null;
            this.partInspectionDrawingAttachments = [];
            this.partInspectionSpecAttachments = [];
            this.assignTo = null;
            this.submittedDate = null;
            this.comment = Constants.Empty;
            this.approveRejected = null;
            this.approveRejectedDate = null;
            this.stateTypeId = null;
            this.addedAdminCertificateIds = [];
            this.removedAdminCertificateIds = [];
            this.assignToUserId = null;
            this.submittedByUserId = null;
            this.approveRejectedId = null;
            this.removedUploadSpecAttachmentsIds = [];
            this.removedDrawingAttachmentIds = [];
            this.removedSpecIds = [];
            this.removedDrawingIds = [];
            this.ismpnMatched = null;
            this.mpnMaterialHERS = Constants.Empty;
            this.mpnReason = Constants.Empty;
            this.partMPositionTolerances = [];
            this.partLPositionTolerances = [];
            this.partMeasurementParameters = [];
            this.partMicrosectionParameters = [];
            this.partFunParameters = [];
            this.partInspectionBowTwistParameters = [];
            this.specTypeId = Numbers.Default;
            this.dataTypeId = Numbers.Default;
            this.partResultOrientedParameters = [];
            this.partTestReportParameters = [];
            this.partCountParameters = [];
            this.partDateCodeId = null;
            this.partInspectionDrawings = [];
            this.partInspectionSpecifications = [];
            this.ipSerialNumber = Numbers.Default;
            this.siteIPSerialNumber = Numbers.Default;
            this.partComments = null;
            this.referenceSAPPartInspectionPlanId = Numbers.Default;
            this.isRedefine = false;
            this.isSupplier = false;
        }
    }
}
